<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk</name>
   <tag></tag>
   <elementGuidId>b919e0a2-52d1-4dea-b09a-c04dd970ea70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.header-login__button.button-s.button-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='navbar']/div/div[3]/div[2]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5836492e-6ad0-495c-990a-bf47dd12067c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-login__button button-s button-secondary</value>
      <webElementGuid>d6177161-3d81-46b2-b747-28bf480eee71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/users/login</value>
      <webElementGuid>6ea18b79-4d5a-4ad9-bc12-be028124963c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>5c8199d2-3fea-4620-a4f3-6b52a5a64491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;site-header__container&quot;]/div[@class=&quot;site-header__right&quot;]/div[@class=&quot;site-header__right-menu js-header-menu-container is-loaded&quot;]/div[@class=&quot;header-login&quot;]/a[@class=&quot;header-login__button button-s button-secondary&quot;]</value>
      <webElementGuid>c9ee4c0c-789e-42f0-894b-180abfc52769</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='navbar']/div/div[3]/div[2]/div/a[2]</value>
      <webElementGuid>fda48bb5-537f-4807-a772-de9d106a7b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Masuk')]</value>
      <webElementGuid>ba564df4-9d9e-4b97-b222-6bca2da53b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Langganan'])[1]/following::a[1]</value>
      <webElementGuid>3d5a7c92-2c47-4b5c-b59c-38bf9b00e77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fantasy Team'])[1]/following::a[2]</value>
      <webElementGuid>cdd14208-9703-4720-962e-6f59c1c0e190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Langganan dan Pembelian'])[1]/preceding::a[1]</value>
      <webElementGuid>5e6a195a-8624-4ff5-9fb1-3b1be2f166bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berlangganan Premier'])[1]/preceding::a[1]</value>
      <webElementGuid>a151efe9-20c8-43a0-a688-7fa0b7d2ca83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>60e7b75b-694f-4a5a-aa10-965b8a9d6ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/users/login')]</value>
      <webElementGuid>a3f808a8-d37e-448f-86b3-e69ef021b0bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>5354ee13-3f6a-4995-ba01-7c5a08d0f22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/users/login' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>ac990db5-b39f-4dc5-b31c-dbec0c01d79d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
